name: Monitor Tools

on:
  schedule:
    # sets the action to run daily. You can modify this to run the action more or less frequently
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  monitor-tools:
    runs-on: ubuntu-latest
    env:
      supabaseKey: ${{ secrets.supabaseKey }}
      supabaseUrl: ${{ secrets.supabaseUrl }}
    defaults:
      run:
        working-directory: ./crawler
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: http://npm.pkg.github.com/
      - run: |
          corepack enable
          pnpm install --frozen-lockfile
          pnpm build
          node dist/src/crawl.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
