name: Monitor Tools

on:
  # schedule:
  #   # sets the action to run daily. You can modify this to run the action more or less frequently
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  monitor-tools:
    runs-on: ubuntu-latest
    env:
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    defaults:
      run:
        working-directory: ./crawler
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: http://npm.pkg.github.com/
      - run: |
          corepack enable
          pnpm install --frozen-lockfile
          pnpm build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          node dist/src/crawl.js

      - name: Archive playright output
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            crawler/crawl-results
