name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crawler
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          # scope: arcticShadow
      - run: |
          ls -la ../ 
          echo $$RUNNER_TEMP
          cat $RUNNER_TEMP/.npmrc
          pwd
          corepack enable
          npm install @arcticshadow/eslint-config

          pnpm install
          pnpm build
