name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./crawler
    steps:
      - run: curl https://www.bunnings.co.nz/ozito-pxc-18v-2-x-4-0ah-batteries-and-charger-pack-pxbc-800c_p0375443

      # - uses: actions/checkout@v4
      #   with:
      #     persist-credentials: false
      #     fetch-depth: 0
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version-file: ".nvmrc"
      #     registry-url: http://npm.pkg.github.com/
      # - env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     corepack enable
      #     pnpm install
      #     pnpm build
